Demande:
    type: entity
    table: demande
    indexes:
        IDX_2694D7A56B3CA4B:
            columns:
                - id_user
        IDX_2694D7A52CF9D259:
            columns:
                - id_stage
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
        idStage:
            targetEntity: Stage
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_stage:
                    referencedColumnName: id_stage
            orphanRemoval: false
    lifecycleCallbacks: {  }
